<?php

/**
 * @file
 * Enables wipe of search index.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function searchindex_wipe_form_search_admin_settings_alter(&$form, &$form_state) {
  $form['status']['clear_index'] = array(
    '#value' => t('Wipe Index'),
    '#type' => 'submit',
    '#submit' => array('searchindex_wipe_all'),
    '#description' => t('Drops all the index build by search module'),
  );
}

/**
 * Truncates all search related tables.
 */
function searchindex_wipe_all(&$form, &$form_state) {
  // Taken code from drupal_uninstall_schema.
  $schema = drupal_get_schema_unprocessed('search');
  foreach ($schema as $table_name => $table) {
    // Truncate search related tables.
    db_truncate($table_name)->execute();
  }
  drupal_set_message(t('Search Index Cleared, Please rebuilt the index by running cron.'));
}

/**
 * Implements hook_help().
 */
function searchindex_wipe_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module.
    case 'admin/config/search/settings':
      return '<p>' . t('Enables clearing of Search related indexes, so that search related tables do not grow large.
      To Re-index the site, You first need to click on Wipe Index button.') . '</p>';
  }
}
