<?php

/**
 * @file
 * Enables wipe of search index.
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
/**
 * Implements hook_form_FORM_ID_alter().
 * @see \Drupal\system\Form\ThemeSettingsForm method buildForm at core/modules/system/src/Form/ThemeSettingsForm.php
 */
function searchindex_wipe_form_search_admin_settings_alter(&$form, FormStateInterface $form_state) {
  if (\Drupal::currentUser()->hasPermission('wipe search index')) {
    $form['status']['clear_index'] = array(
      '#value' => t('Wipe Index'),
      '#type' => 'submit',
      '#submit' => array('searchindex_wipe_all'),
      '#description' => t('Drops all the index build by search module'),
    );
  }
}

/**
 * Redirect to confirmation link.
 */
function searchindex_wipe_all(&$form, FormStateInterface $form_state) {
  $url = new Url('searchindex_wipe.reindex_confirm');
  $form_state->setRedirectUrl($url);
}